[package]
name = "jet"
version = "0.1.0"
edition = "2024"

[dependencies]
flexi_logger = "0.31.8"
goblin = { git = "https://github.com/amgdev9/goblin" }
hex = "0.4.3"
log = "0.4.29"
range-alloc = "0.1.4"
unicorn-engine = "2.1.5"
