[package]
name = "jet"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin = { git = "https://github.com/amgdev9/goblin" }
hex = "0.4.3"
log = "0.4.29"
simplelog = "0.12.2"
unicorn-engine = "2.1.5"
